version: '3'

services:
  mongodb:
    image: sangkuriang/mongodb
    container_name: sangkuriang-mongo
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
        - 27017:27017

volumes:
  mongodb:
  mongodb_config: